export const GOOGLE_MAPS_API_KEY = process.env.REACT_APP_GOOGLE_MAPS_API_KEY;
export const STRAVA_SECRET = process.env.REACT_APP_STRAVA_SECRET;
export const GEOCODING_API_KEY = process.env.REACT_APP_GEOCODING_API_KEY;
